### ISSUE TITLE
ms_dotnet 3.2.1 fails patch install for .net4.6.2

### ISSUE THREAD

**Issue by Stromweld** [criteo-cookbooks/ms_dotnet#54]
On windows server 2012 r2 with chef-client 12.19.36 I'm getting the below error after the latest update changed the order of a couple of patch installs. Previous 3.2.0 version of this cookbook worked fine.

```
Recipe: ms_dotnet::ms_dotnet4
  * ms_dotnet_framework[4.6.2] action install
    * windows_package[Update for Microsoft Windows (KB2919442)] action install
    Recipe: <Dynamically Defined Resource>
      * remote_file[C:\chef\cache\package\Windows8.1-KB2919442-x64.msu] action create (up to date)

      ================================================================================
      Error executing action `install` on resource 'windows_package[Update for Microsoft Windows (KB2919442)]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0, 3010], but received '-2145124329'
      ---- Begin output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exi
t %%%%ERRORLEVEL%%%% ----
      STDOUT:
      STDERR:
      ---- End output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit
%%%%ERRORLEVEL%%%% ----
      Ran start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit %%%%ERRORLEVEL%
%%% returned -2145124329

      Resource Declaration:
      ---------------------
      # In C:/chef/cache/cookbooks/ms_dotnet/resources/framework.rb

       77:       windows_package pkg[:name] do # ~FC009 ~FC022
       78:         action          :install
       79:         installer_type  :custom
       80:         success_codes   [0, 3010] if respond_to? :success_codes
       81:         returns         [0, 3010] if respond_to? :returns
       82:         options         pkg[:options] || '/q /norestart'
       83:         timeout         new_resource.timeout
       84:         # Package specific info
       85:         checksum        pkg[:checksum]
       86:         source          new_resource.package_sources[pkg[:checksum]] || pkg[:url]
       87:         not_if          pkg[:not_if] unless pkg[:not_if].nil?
       88:       end
       89:

      Compiled Resource:
      ------------------
      # Declared in C:/chef/cache/cookbooks/ms_dotnet/resources/framework.rb:77:in `block in install_packages'

      windows_package("Update for Microsoft Windows (KB2919442)") do
        package_name "Update for Microsoft Windows (KB2919442)"
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        source "https://download.microsoft.com/download/D/6/0/D60ED3E0-93A5-4505-8F6A-8D0A5DA16C8A/Windows8.1-KB2919442-
x64.msu"
        declared_type :windows_package
        cookbook_name "ms_dotnet"
        options "/norestart /quiet"
        timeout 600
        returns [0, 3010]
        installer_type :custom
        checksum "c10787e669b484674584a990e069295e8b81b5366f98508010a3ae181b729482"
        not_if "C:\Windows\System32\wbem\wmic.exe QFE where HotFixID='KB2919442' | FindStr KB2919442"
      end

      Platform:
      ---------
      x64-mingw32


    ================================================================================
    Error executing action `install` on resource 'ms_dotnet_framework[4.6.2]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    windows_package[Update for Microsoft Windows (KB2919442)] (C:/chef/cache/cookbooks/ms_dotnet/resources/framework.rb
line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 3010], but received '-214
5124329'
    ---- Begin output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit
%%%%ERRORLEVEL%%%% ----
    STDOUT:
    STDERR:
    ---- End output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit %%
%%ERRORLEVEL%%%% ----
    Ran start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit %%%%ERRORLEVEL%%%
% returned -2145124329

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/ms_dotnet/recipes/ms_dotnet4.rb

     24: ms_dotnet_framework v4_info['version'] do
     25:   timeout           node['ms_dotnet']['timeout']
     26:   include_patches   v4_info['include_patches']
     27:   feature_source    v4_info['feature_source'] unless v4_info['feature_source'].nil?
     28:   perform_reboot    v4_info['perform_reboot']
     29:   package_sources   v4_info['package_sources']
     30:   require_support   v4_info['require_support']
     31: end

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/ms_dotnet/recipes/ms_dotnet4.rb:24:in `from_file'

    ms_dotnet_framework("4.6.2") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :ms_dotnet_framework
      cookbook_name "ms_dotnet"
      recipe_name "ms_dotnet4"
      timeout 600
      include_patches true
      perform_reboot false
      package_sources {}
      require_support false
      version "4.6.2"
    end

    Platform:
    ---------
    x64-mingw32


Running handlers:
Running handlers complete
Chef Client failed. 2 resources updated in 37 seconds
```

**Comment by Stromweld** [comment]
even after setting the attribute to install patches to false it looks like it's still trying and failing:
```
Recipe: ms_dotnet::ms_dotnet4
  * ms_dotnet_framework[4.6.2] action install
    * windows_package[Update for Microsoft Windows (KB2919442)] action install
    Recipe: <Dynamically Defined Resource>
      * remote_file[C:\chef\cache\package\Windows8.1-KB2919442-x64.msu] action create (up to date)

      ================================================================================
      Error executing action `install` on resource 'windows_package[Update for Microsoft Windows (KB2919442)]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0, 3010], but received '-2145124329'
      ---- Begin output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exi
t %%%%ERRORLEVEL%%%% ----
      STDOUT:
      STDERR:
      ---- End output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit
%%%%ERRORLEVEL%%%% ----
      Ran start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit %%%%ERRORLEVEL%
%%% returned -2145124329

      Resource Declaration:
      ---------------------
      # In C:/chef/cache/cookbooks/ms_dotnet/resources/framework.rb

       77:       windows_package pkg[:name] do # ~FC009 ~FC022
       78:         action          :install
       79:         installer_type  :custom
       80:         success_codes   [0, 3010] if respond_to? :success_codes
       81:         returns         [0, 3010] if respond_to? :returns
       82:         options         pkg[:options] || '/q /norestart'
       83:         timeout         new_resource.timeout
       84:         # Package specific info
       85:         checksum        pkg[:checksum]
       86:         source          new_resource.package_sources[pkg[:checksum]] || pkg[:url]
       87:         not_if          pkg[:not_if] unless pkg[:not_if].nil?
       88:       end
       89:

      Compiled Resource:
      ------------------
      # Declared in C:/chef/cache/cookbooks/ms_dotnet/resources/framework.rb:77:in `block in install_packages'

      windows_package("Update for Microsoft Windows (KB2919442)") do
        package_name "Update for Microsoft Windows (KB2919442)"
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        source "https://download.microsoft.com/download/D/6/0/D60ED3E0-93A5-4505-8F6A-8D0A5DA16C8A/Windows8.1-KB2919442-
x64.msu"
        declared_type :windows_package
        cookbook_name "ms_dotnet"
        options "/norestart /quiet"
        timeout 600
        returns [0, 3010]
        installer_type :custom
        checksum "c10787e669b484674584a990e069295e8b81b5366f98508010a3ae181b729482"
        not_if "C:\Windows\System32\wbem\wmic.exe QFE where HotFixID='KB2919442' | FindStr KB2919442"
      end

      Platform:
      ---------
      x64-mingw32


    ================================================================================
    Error executing action `install` on resource 'ms_dotnet_framework[4.6.2]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    windows_package[Update for Microsoft Windows (KB2919442)] (C:/chef/cache/cookbooks/ms_dotnet/resources/framework.rb
line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 3010], but received '-214
5124329'
    ---- Begin output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit
%%%%ERRORLEVEL%%%% ----
    STDOUT:
    STDERR:
    ---- End output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit %%
%%ERRORLEVEL%%%% ----
    Ran start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu"   /norestart /quiet & exit %%%%ERRORLEVEL%%%
% returned -2145124329

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/ms_dotnet/recipes/ms_dotnet4.rb

     24: ms_dotnet_framework v4_info['version'] do
     25:   timeout           node['ms_dotnet']['timeout']
     26:   include_patches   v4_info['include_patches']
     27:   feature_source    v4_info['feature_source'] unless v4_info['feature_source'].nil?
     28:   perform_reboot    v4_info['perform_reboot']
     29:   package_sources   v4_info['package_sources']
     30:   require_support   v4_info['require_support']
     31: end

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/ms_dotnet/recipes/ms_dotnet4.rb:24:in `from_file'

    ms_dotnet_framework("4.6.2") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :ms_dotnet_framework
      cookbook_name "ms_dotnet"
      recipe_name "ms_dotnet4"
      timeout 600
      include_patches false
      perform_reboot false
      package_sources {}
      require_support false
      version "4.6.2"
    end

    Platform:
    ---------
    x64-mingw32


Running handlers:
Running handlers complete
Chef Client failed. 2 resources updated in 37 seconds
```

**Comment by Annih** [comment]
Humm the `include_patches` issue is definitely a recent and unknown bug... I'll have a look at it
For the KB2919442 this is related to #45, #50  & #51 

If you have time to help, please test #51 branch, thanks!

**Comment by Annih** [comment]
Hello @Stromweld 

I just read my code again, and I have an answer for the `include_patches` issue!
Sadly this is not an issue... `KB2919442` is not a patch over .NET 4.6, it is a prerequisites!

That's why setting `include_patches` to `false` does not prevent this error.

Don't worry I'll still work on KB error in #51 !

Regards.

**Comment by Stromweld** [comment]
yeah I haven't had much time to dig into yet myself. I'm hoping next week I'll have more time to help test #51 and see if I can help with the issue.

**Comment by steveoh** [comment]
Would the https://docs.chef.io/resource_msu_package.html help? This is biting me at the moment.

**Comment by Annih** [comment]
@steveoh the `msu_package` resource is overkill I won't try to use it.
Normally all required patches are merged into master to fix the current issue, could you try it? or wait until the next release.

**Comment by steveoh** [comment]
So you think the current fix is in master then?

**Comment by steveoh** [comment]
I can verify that 4.6.1 was installed successfully from master on server 2012r2. It does require a reboot if things require it later in the run list. Is that expected or required?

**Comment by Annih** [comment]
@steveoh the version 4.0.0 of *ms_dotnet* cookbook has been released, could you try it and tell me if you still encounter your issue?

**Comment by Annih** [comment]
@steveoh any change you have been able to test version 4.0.0?

**Comment by steveoh** [comment]
Not yet but I should be able to at some point next week I hope.

**Comment by nicutor** [comment]
Hi,

I am getting this error when trying to install 4.0 on Windows 7. Is there a way to fix this or an alternative to do it? Thanks

```

       Recipe: ms_dotnet::ms_dotnet4
         * ms_dotnet_framework[4.0] action install
           * windows_package[Microsoft .NET Framework 4 Extended] action install
           Recipe: <Dynamically Defined Resource>
             * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\dotNetFx40_Full_x86_x64.exe] action create
        - create new file C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\dotNetFx40_Full_x86_x64.exe
        - update content in file C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\dotNetFx40_Full_x86_x64.exe from none to 65e064
        (file sizes exceed 10000000 bytes, diff output suppressed)

             ================================================================================
             Error executing action `install` on resource 'windows_package[Microsoft .NET Framework 4 Extended]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0, 3010], but received '5'
             ---- Begin output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /noresta
rt & exit %%%%ERRORLEVEL%%%% ----
             STDOUT:
             STDERR:
             ---- End output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /norestart
 & exit %%%%ERRORLEVEL%%%% ----
             Ran start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /norestart & exit %%%%ERR
ORLEVEL%%%% returned 5

             Resource Declaration:
             ---------------------
             # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ms_dotnet/resources/framework.rb

       83:       windows_package pkg[:name] do # ~FC009 ~FC022
       84:         action          :install
       85:         installer_type  :custom
       86:         success_codes   [0, 3010] if respond_to? :success_codes
       87:         returns         [0, 3010] if respond_to? :returns
       88:         options         pkg[:options] || '/q /norestart'
       89:         timeout         new_resource.timeout
       90:         # Package specific info
       91:         checksum        pkg[:checksum]
       92:         source          new_resource.package_sources[pkg[:checksum]] || pkg[:url]
       93:         # Handle not_if guards
       94:         case pkg[:not_if]
       95:           when String # Execute the given string guard
       96:             not_if      pkg[:not_if]
       97:           when Array # Ensure given array of QFE KB is not installed
       98:             # Some packages are installed as QFE updates on 2012, 2012R2 & 10 or may have been superseded by other updates
       99:             not_if do
             100:               require 'wmi-lite'
             101:               filter = pkg[:not_if].map { |kb| " HotFixID='#{kb}'" }.join(' OR')
             102:               !filter.empty? && ::WmiLite::Wmi.new.query("SELECT HotFixID FROM Win32_QuickFixEngineering WHERE #{filter}").any?
             103:             end
             104:         end
             105:         # Perform automatic reboot now, if required

             Compiled Resource:
             ------------------
             # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ms_dotnet/resources/framework.rb:83:in `block in install_packag
es'

             windows_package("Microsoft .NET Framework 4 Extended") do
        package_name "Microsoft .NET Framework 4 Extended"
        action [:install]
        default_guard_interpreter :default
        declared_type :windows_package
        cookbook_name "ms_dotnet"
        installer_type :custom
        returns [0, 3010]
        options "/q /norestart"
        timeout 600
        checksum "65e064258f2e418816b304f646ff9e87af101e4c9552ab064bb74d281c38659f"
        source "https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe"
             end

             System Info:
             ------------
             chef_version=13.4.24
             platform=windows
             platform_version=6.1.7600
             ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
             program_name=C:/opscode/chef/bin/chef-client
             executable=C:/opscode/chef/bin/chef-client


           ================================================================================
           Error executing action `install` on resource 'ms_dotnet_framework[4.0]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           windows_package[Microsoft .NET Framework 4 Extended] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ms_dotnet/resources/frame
work.rb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 3010], but received '5'
           ---- Begin output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /norestart
 & exit %%%%ERRORLEVEL%%%% ----
           STDOUT:
           STDERR:
           ---- End output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /norestart &
 exit %%%%ERRORLEVEL%%%% ----
           Ran start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /norestart & exit %%%%ERROR
LEVEL%%%% returned 5

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ms_dotnet/recipes/ms_dotnet4.rb

            24: ms_dotnet_framework v4_info['version'] do
            25:   timeout           node['ms_dotnet']['timeout']
            26:   include_patches   v4_info['include_patches']
            27:   feature_source    v4_info['feature_source'] unless v4_info['feature_source'].nil?
            28:   perform_reboot    v4_info['perform_reboot']
            29:   package_sources   v4_info['package_sources']
            30:   require_support   v4_info['require_support']
            31: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ms_dotnet/recipes/ms_dotnet4.rb:24:in `from_file'

           ms_dotnet_framework("4.0") do
             action [:install]
             default_guard_interpreter :default
             declared_type :ms_dotnet_framework
             cookbook_name "ms_dotnet"
             recipe_name "ms_dotnet4"
             timeout 600
             include_patches true
             perform_reboot false
             package_sources {}
             require_support false
           end

           System Info:
           ------------
           chef_version=13.4.24
           platform=windows
           platform_version=6.1.7600
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client


       Running handlers:
       [2017-09-27T11:27:12-07:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-09-27T11:27:12-07:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 01 minutes 15 seconds
       [2017-09-27T11:27:12-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-09-27T11:27:12-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-09-27T11:27:12-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: ms_dotnet_framework[4.0] (ms_dotnet::ms_dotnet4 line 24) had an error:
 Mixlib::ShellOut::ShellCommandFailed: windows_package[Microsoft .NET Framework 4 Extended] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookboo
ks/ms_dotnet/resources/framework.rb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 3010], but received
 '5'
       ---- Begin output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /norestart & e
xit %%%%ERRORLEVEL%%%% ----
       STDOUT:
       STDERR:
       ---- End output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /norestart & exi
t %%%%ERRORLEVEL%%%% ----
       Ran start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\dotnetfx40_full_x86_x64.exe"   /q /norestart & exit %%%%ERRORLEVE
L%%%% returned 5

```

**Comment by Annih** [comment]
Hello @nicutor 
This is clearly not related to current issue.

The error code 5 referes to an *access denied* error. Please read the [known issue section of the readme](https://github.com/criteo-cookbooks/ms_dotnet#known-issues) for the workarounds

**Comment by Annih** [comment]
Hello @steveoh, did you reproduce the issue?

**Comment by steveoh** [comment]
Sorry I haven't made time.

**Comment by Annih** [comment]
@steveoh any news? I'm considering closing this issue soon.

**Comment by steveoh** [comment]
I'm not going to test. You can close this. If I decide to try chef again, I'll open more issues :)

**Comment by Annih** [comment]
Ok thanks for the honest answer, I'm closing it. Enjoy your new adventures if you left the Chef world!
